manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: chastity-zmk
      url: https://github.com/brad-za/chastity-zmk
      revision: main
  self:
    path: config
